export const places = [
    "Alvariini",
    "Aninkaisten Keilahalli",
    "Aquarius Bowling",
    "Arena Center Myllypuro",
    "Aulangon keilahalli",
    "Bowl D1ner",
    "BowlCircus Flamingo",
    "BowlCircus Sello",
    "BowlCircus Vuokatti",
    "Bowling House - Nurmijärvi",
    "Cinema Bowling",
    "CornerClub",
    "Downtown Bowling",
    "Eurajoen Keilahalli",
    "Euran Keilahalli",
    "Forssan Keilahalli",
    "Fun Bowling",
    "Gr8 Bowl Vierumäki",
    "Gr8 Pöllö -Ylläs",
    "Gr8 Salmisaari",
    "Haapajärven Keilahalli",
    "Hangon Keilahalli",
    "Hanhivaaran keilahalli",
    "Happy Family Bowling",
    "Heinolan Keilahalli/Valopallo Oy",
    "Hiitteenharjun keilahalli",
    "Huittisten Keila- ja Pelihalli",
    "Hutungin Keilahalli",
    "Hyvinkään Keilahalli",
    "Hämeenlinnan Keilahalli",
    "Iisalmen keilahalli",
    "Imatran Keilahalli",
    "Imatran Kylpylän keilahalli",
    "Joensuun Keilahalli/Joensuun Kuntokeidas",
    "Jyväskylän Keilahalli",
    "Järvenpään keilahalli",
    "Gr8 Kaatopaikka",
    "Kaikki Suomen keilahallit",
    "Kajaanin Keila-keskus Oy/ Puisto - bowling-food-friends",
    "Kalajoen Keilahalli",
    "Kampin keilahalli",
    "Kankaanpään keilahalli",
    "Karstulan Täyskaato",
    "Katinkullan Keilahalli",
    "Kauhajoen Keilahalli",
    "Kaupin keilahalli",
    "Keila- ja tenniskeskus Pelixir",
    "Keilaamo",
    "Keilahalli Siilinhohto",
    "Keilahalli/Ravintola Kaato",
    "Keilarysä/Viitasaaren Viihdekeskus",
    "Keilaukko(Ukkohallan keilahalli",
    "Kemin Keila- ja Tennishalli",
    "Keravan Keilahalli",
    "Keuruun Keillahalli",
    "Kiitorata",
    "Kiuruveden keilahalli",
    "Kokkola Sports Club & Donna",
    "Kokkolan Keilahalli",
    "Kotkan Keilahalli",
    "Kouvolan Keilahalli",
    "Kruunupyyn keilahalli",
    "Kuopion Keilahalli",
    "Kuortaneen keilahalli",
    "Kupittaan Keilahalli",
    "Kurikan keilahallli",
    "Kuusamon keilahalli",
    "Kuusamon Tropiikki/keilahalli",
    "Kuusankosken Keilahalli",
    "Laajavuoren keilahalli",
    "Lahden Hohtokeila",
    "Lahden Keilahalli",
    "Lappeenrannan keilahalli",
    "Leppävirran keilahalli",
    "Levi Gold",
    "Levi SPA Bowling",
    "Lippulaiva Bowling Billiard",
    "Lohjan Keilahalli",
    "Loimaan keilahalli",
    "Lomakeskus Revontuli",
    "Lomamajat Korven Kummajainen ja keilahalli",
    "Loviisan Keilahalli",
    "LähiTapiola Sport Center /Kirkkonummen keilahalli",
    "Mariehamns bowlinghall",
    "Mikkelin keilahalli",
    "Mäntän Keilahalli",
    "Nakkilan Keilahalli",
    "Nivalan Liikuntakeskus",
    "Närpes Bowlinghall / Närpiön Keilahalli",
    "Oulun keilahalli",
    "Paraisten keilahalli",
    "Pelixir Kempele",
    "Pelixir - Oulu",
    "Pietarsaaren Keilahalli",
    "Piispalan keilahalli",
    "Players Sports Bar",
    "Porin Keilahalli",
    "Porvoon keilahalli",
    "Punkaharjun Keilahalli",
    "Pyhäjärven keilahalli",
    "Raahen keilahalli",
    "Raision keilahalli",
    "Rauhalahti Bowling",
    "Rauman keilahalli",
    "Riihimäen keilahalli",
    "Rovaniemen Keilahalli/Santasport",
    "Ruusulan Keilahalli",
    "Saarijärven keilahali",
    "Sallan keilahalli",
    "Salon Keilahalli",
    "Savonlinnan Keilahalli",
    "Simpeleen Keilahalli",
    "Someron keilahalli",
    "Space Bowling",
    "Space Bowling & Billiards",
    "Squash & Bowling Center Seinäjoki",
    "Sysmän Keilahalli",
    "Tahko Bowling",
    "Talin Keilahalli",
    "Tammisaaren Keilahalli",
    "Tapanilan Keilahalli",
    "Tapiolan keilahalli",
    "The Castle Inn",
    "Tikkurilan Keilahalli",
    "Tornion Keilahalli",
    "Tuusulan keilahalli",
    "Vaasan Keilahalli",
    "Valkeakosken keilahalli",
    "Varkauden Keilahalli",
    "Vihti Bowling",
    "Viihdekeilahalli Cosmic",
    "Viihdekeskus Huvila",
    "Viihdekeskus Liikelataamo",
    "Vöyrin Keilahalli",
    "Ylivieskan Keilahalli",
    "Ylöjärven Keilahalli",
    "Äänekosken Keilahalli"
]


export default { places } 